Models/ErrorViewModel.cs
namespace SkillExpose2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Game.cs
namespace SkillExpose2.Models
{
    public class Game
    {
        public int GameID { get; set; }
        public string Name { get; set; }
    }
}

Models/Skill.cs
namespace SkillExpose2.Models
{
    public class Skill
    {
        public int ID { get; set; }
        public string Name { get; set; } = "";
        public int GameID { get; set; }
        public string Game { get; set; } = "";
        public string Type { get; set; } = "";
        public string InGameDescription { get; set; } = "";
        public string AdditionalDescription { get; set; } = "";
        public string Notes { get; set; } = "";
        public string YTVideoName { get; set; } = "";
        public string YTCode { get; set; } = "";
        public string TSStart { get; set; } = "";
        public string TSEnd { get; set; } = "";
        public IEnumerable<Game> Games { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SkillExpose2.Models;
using System.Diagnostics;

namespace SkillExpose2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using SkillExpose2.Models;

namespace SkillExpose2.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillRepository repo;
        
        public SkillController(ISkillRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var skills = repo.GetAllSkills();

            return View(skills);
        }

        public IActionResult ViewSkill(int id)
        {
            var skill = repo.GetSkill(id);

            return View(skill);
        }

        public IActionResult UpdateSkill(int id)
        {
            Skill skill = repo.GetSkill(id);

            if (skill == null)
            {
                return View("SkillNotFound");
            }

            return View(skill);
        }

        public IActionResult UpdateSkillToDatabase(Skill skill)
        {
            repo.UpdateSkill(skill);

            return RedirectToAction("ViewSkill", new { id = skill.ID });
        }

        public IActionResult InsertSkill()
        {
            var skill = repo.AssignCategory();

            return View(skill);
        }

        public IActionResult InsertSkillToDatabase(Skill skill)
        {
            repo.InsertSkill(skill);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteSkill(Skill skill)
        {
            repo.DeleteSkill(skill);
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SkillExpose2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SkillExpose2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SkillExpose2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skill" asp-action="Index">Skills</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SkillExpose2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Skill/Index.cshtml
@model IEnumerable<Skill>

<h2>Skills</h2>

<div style="display: block">
    <a href="/Skill/InsertSkill/">Create a New Product</a>
</div>

<table class="table">
    <tr>
        <th>Name</th>
    </tr>

    @foreach (var skill in Model)
    {
        <tr>
            <td><a href=/Skill/ViewSkill/@skill.ID>@skill.Name</a></td>
        </tr>
    }

</table>

Views/Skill/InsertSkill.cshtml
@model Skill

<h2>Create a New Skill</h2>

@using (Html.BeginForm("InsertSkillToDatabase", "Skill", "Post"))
{
    <input asp-for="ID" type="hidden" value="" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="" />

    <div class="form-group">
        <label for="">Select a Game</label>
        <select class="form-control" name="Game" value="">
            @foreach (var game in Model.Games)
            {
                <option value="@game.Name">@game.GameID @game.Name</option>
            }
        </select>
    </div>

    <label asp-for="GameID" class="control-label">Input GameID shown above:</label>
    <input type="text" name="GameID" class="form-control" value="" />

    <label asp-for="Type" class="control-label">Type</label>
    <input type="text" name="Type" class="form-control" value="" />

    <label asp-for="InGameDescription" class="control-label">InGameDescription</label>
    <input type="text" name="InGameDescription" class="form-control" value="" />

    <label asp-for="AdditionalDescription" class="control-label">AdditionalDescription</label>
    <input type="text" name="AdditionalDescription" class="form-control" value="" />

    <label asp-for="Notes" class="control-label">Notes</label>
    <input type="text" name="Notes" class="form-control" value="" />

    <label asp-for="YTVideoName" class="control-label">YTVideoName</label>
    <input type="text" name="YTVideoName" class="form-control" value="" />

    <label asp-for="YTCode" class="control-label">YTCode</label>
    <input type="text" name="YTCode" class="form-control" value="" />

    <label asp-for="TSStart" class="control-label">TSStart</label>
    <input type="text" name="TSStart" class="form-control" value="" />

    <label asp-for="TSEnd" class="control-label">TSEnd</label>
    <input type="text" name="TSEnd" class="form-control" value="" />

    <input type="submit" value="Create Skill" class="btn btn-primary" />
}

Views/Skill/UpdateSkill.cshtml
@model Skill

<h2>Update @Model.Name</h2>

@using (Html.BeginForm("UpdateSkillToDatabase", "Skill", "Post"))
{
    <input asp-for="ID" type="hidden" value="@Model.ID" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="GameID" class="control-label">GameID</label>
    <input type="text" name="GameID" class="form-control" value="@Model.GameID" />

    <label asp-for="Game" class="control-label">Game</label>
    <input type="text" name="Game" class="form-control" value="@Model.Game" />

    <label asp-for="Type" class="control-label">Type</label>
    <input type="text" name="Type" class="form-control" value="@Model.Type" />

    <label asp-for="InGameDescription" class="control-label">InGameDescription</label>
    <input type="text" name="InGameDescription" class="form-control" value="@Model.InGameDescription" />

    <label asp-for="AdditionalDescription" class="control-label">AdditionalDescription</label>
    <input type="text" name="AdditionalDescription" class="form-control" value="@Model.AdditionalDescription" />

    <label asp-for="Notes" class="control-label">Notes</label>
    <input type="text" name="Notes" class="form-control" value="@Model.Notes" />

    <label asp-for="YTVideoName" class="control-label">YTVideoName</label>
    <input type="text" name="YTVideoName" class="form-control" value="@Model.YTVideoName" />

    <label asp-for="YTCode" class="control-label">YTCode</label>
    <input type="text" name="YTCode" class="form-control" value="@Model.YTCode" />

    <label asp-for="TSStart" class="control-label">TSStart</label>
    <input type="text" name="TSStart" class="form-control" value="@Model.TSStart" />

    <label asp-for="TSEnd" class="control-label">TSEnd</label>
    <input type="text" name="TSEnd" class="form-control" value="@Model.TSEnd" />

    <input type="submit" value="Update Skill" class="btn btn-primary" />
}

Views/Skill/ViewSkill.cshtml
@model Skill

<h3>@Model.Name Information</h3>

<table class="table">
    <tr>
        <th>Skill ID</th>
        <th>Name</th>
        <th>Game</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>@Model.ID</td>
        <td>@Model.Name</td>
        <td>@Model.Game</td>
        <td>@Model.InGameDescription</td>
    </tr>

</table>

<div style="display: block">
    <a href="/Skill/UpdateSkill/@Model.ID">UPDATE THIS SKILL</a>
</div>

<div style="display: block">

    @using (Html.BeginForm("DeleteSkill", "Skill", "Post"))
    {
        <input type="hidden" asp-for="ID" value="@Model.ID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this product" />
    }
</div>